"""first

Revision ID: 8546557970c4
Revises: 
Create Date: 2022-02-04 04:55:04.352326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8546557970c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('security_name', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Numeric(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
