"""status to file

Revision ID: e41718829d62
Revises: 2e29fee4851b
Create Date: 2022-02-04 06:23:35.950211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41718829d62'
down_revision = '2e29fee4851b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'status')
    # ### end Alembic commands ###
